const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const width of [320,390]){
 const p=await browser.newPage({viewport:{width,height:700},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();if(u.pathname.startsWith('/api/'))return r.fulfill({contentType:'application/json',body:'{"events":[]}'});const f=path.join(process.cwd(),'docs',u.pathname);if(!fs.existsSync(f))return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:({'.html':'text/html','.css':'text/css','.js':'text/javascript'})[path.extname(f)]||'text/plain'});});
 await p.goto('http://127.0.0.1/mini-app.html?preview=1',{waitUntil:'networkidle'});
 const brandBefore=await p.locator('h1.welcome-brand').boundingBox();
 assert.equal(await p.locator('#welcome-gate').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(23, 27, 54, 0.8)');
 assert.match(await p.locator('#welcome-gate').evaluate(e=>getComputedStyle(e).backgroundImage),/linear-gradient/);
 await p.screenshot({path:'.tools/welcome-gradient-'+width+'.png'});
 assert.equal(await p.locator('#welcome-gate').evaluate(e=>getComputedStyle(e,'::before').display),'none');
 await p.locator('#welcome-gate button').filter({hasText:/^Войти$/}).click();
 assert(await p.locator('[data-verify-slider]').isDisabled());
 assert(await p.locator('#panel > .close').isHidden(),'No round close button in login coupon');
 assert(await p.locator('.auth-keypad').isHidden(),'Keypad hidden before generation');
 const compactBox=await p.locator('#panel').boundingBox();assert(compactBox.height<210,'Three-row bottom coupon');
 await p.screenshot({path:'.tools/auth-coupon-compact-'+width+'.png'});
 assert.equal(await p.locator('#panel').evaluate(e=>getComputedStyle(e,'::backdrop').backgroundColor),'rgba(0, 0, 0, 0)');
 assert.deepEqual(await p.locator('h1.welcome-brand').boundingBox(),brandBefore,'Opening sheet must not move the logo');
 assert(await p.locator('.auth-entry-caret').isVisible(),'Caret visible immediately');
 assert.equal(await p.locator('.auth-lock.is-unlocked').count(),0);
 await p.clock.install();
 await p.clock.pauseAt(new Date(Date.now()+1000));
 await p.mouse.click(10,100);assert(!(await p.locator('#panel').evaluate(e=>e.open)),'Outside tap closes coupon');
 await p.locator('.welcome-login').click();await p.keyboard.press('Escape');
 assert(!(await p.locator('#panel').evaluate(e=>e.open)),'Escape closes coupon');
 await p.locator('.welcome-login').click();
 assert(await p.locator('.auth-keypad').isHidden(),'Keypad hidden after reopening');
 assert.match(await p.locator('[data-code-source]').innerText(),/^\d\.\d{2}$/);
 assert.equal(await p.locator('.auth-quote').count(),0,'Middle event removed');
 assert.equal(await p.locator('.auth-generate .auth-lock').count(),1,'Lock moved to first event');
 assert(await p.locator('[data-auth-key="1"]').isDisabled());
 await p.emulateMedia({reducedMotion:'no-preference'});
 assert.equal(await p.locator('.auth-entry-caret').evaluate(e=>getComputedStyle(e).animationName),'none');
 assert.equal(await p.locator('[data-auth-key="."],[data-auth-key=","]').count(),0);
 assert.deepEqual(await p.locator('[data-auth-key]').evaluateAll(es=>es.map(e=>e.dataset.authKey)),['1','2','3','4','5','6','7','8','9','0','⌫']);
 assert.equal(await p.locator('[data-auth-key="⌫"] svg path').count(),2);
 await p.clock.runFor(1999);assert(await p.locator('[data-auth-key="1"]').isDisabled());
 assert(await p.locator('.auth-keypad').isHidden(),'Drawer stays hidden for full generation');
 await p.clock.runFor(1);assert(!(await p.locator('[data-auth-key="1"]').isDisabled()));
 assert(await p.locator('.auth-keypad').isVisible(),'Drawer appears after generation');
 assert.equal(await p.locator('.welcome-coupon .auth-keypad').count(),0,'Keyboard is outside coupon');
 await p.clock.runFor(400);
 await p.clock.resume();
 const code=await p.locator('[data-code-source]').innerText();assert.match(code,/^\d\.\d{2}$/);
 assert.equal(await p.locator('[data-code-generate]').innerText(),code);
 assert.equal(await p.locator('.auth-entry-caret').evaluate(e=>getComputedStyle(e).animationName),'auth-caret-blink');
 await p.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await p.locator('.auth-generate .auth-card-end').innerText(),'');
 assert(await p.locator('.auth-generate').evaluate(e=>e.querySelector('[data-code-source]').getBoundingClientRect().left<e.querySelector('.auth-card-end').getBoundingClientRect().left));
 assert.equal(await p.locator('[data-code-entry]').getAttribute('placeholder'),'Введите сгенерированный код');
 assert(await p.locator('.auth-entry-caret').isVisible());
 assert.equal(await p.locator('[data-code-entry]').evaluate(e=>getComputedStyle(e).outlineStyle),'none');
 assert.equal(await p.locator('[data-code-source]').evaluate(e=>getComputedStyle(e).animationName),'none');
 await p.emulateMedia({reducedMotion:'no-preference'});
 assert.equal(await p.locator('[data-code-source]').evaluate(e=>getComputedStyle(e).animationName),'none');
 assert.equal(await p.locator('.auth-generate').evaluate(e=>getComputedStyle(e).animationName),'none');
 assert.equal(await p.locator('.auth-generate').evaluate(e=>getComputedStyle(e).borderTopColor),'rgb(112, 189, 139)');
 assert.equal(await p.locator('.auth-entry-row').evaluate(e=>getComputedStyle(e).borderTopColor),'rgb(216, 217, 226)');
 assert.equal(await p.locator('.auth-dial-dots circle').count(),10);
 await p.emulateMedia({reducedMotion:'reduce'});
 await p.screenshot({path:'.tools/auth-coupon-empty-'+width+'.png'});
 await p.locator('[data-auth-key="0"]').click();assert(await p.locator('[data-verify-slider]').isDisabled());await p.locator('[data-auth-key="⌫"]').click();
 await p.locator(`[data-auth-key="${code[0]}"]`).click();assert.equal(await p.locator('[data-code-entry]').inputValue(),code[0]+'.');
 await p.locator('[data-auth-key="⌫"]').click();assert.equal(await p.locator('[data-code-entry]').inputValue(),'');
 for(const k of code.replace('.',''))await p.locator(`[data-auth-key="${k}"]`).click();
 assert.equal(await p.locator('[data-code-entry]').inputValue(),code);
 assert(!(await p.locator('[data-verify-slider]').isDisabled()));
 assert.equal(await p.locator('.auth-entry-row').evaluate(e=>getComputedStyle(e).borderTopColor),'rgb(112, 189, 139)');
 assert.equal(await p.locator('.auth-entry-row').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');
 assert.equal(await p.locator('.auth-lock.is-unlocked').count(),1);
 await p.locator('[data-auth-key="⌫"]').click();assert.equal(await p.locator('.auth-lock.is-unlocked').count(),0);
 await p.locator(`[data-auth-key="${code.at(-1)}"]`).click();assert.equal(await p.locator('.auth-lock.is-unlocked').count(),1);
 await p.screenshot({path:'.tools/auth-coupon-'+width+'.png'});
 assert(await p.locator('.welcome-coupon').evaluate(e=>e.scrollHeight<=e.clientHeight+1),'Coupon must fit without scrolling');
 const gap=await p.evaluate(()=>document.querySelector('#panel').getBoundingClientRect().top-document.querySelector('.welcome-brand').getBoundingClientRect().bottom);assert(gap>=10,'Sheet must stay below logo: '+gap);
 const couponBox=await p.locator('.welcome-coupon').boundingBox(),drawerBox=await p.locator('.auth-keyboard-drawer').boundingBox();
 assert.equal(couponBox.y,compactBox.y,'Coupon remains stationary');
 assert(drawerBox.y+drawerBox.height<=couponBox.y-10,'Floating keypad above coupon');
 assert(drawerBox.y>=brandBefore.y+brandBefore.height+10,'Keyboard clears logo');
 assert(drawerBox.x>width/2,'Keyboard on the right');
 assert.equal(await p.locator('.auth-keyboard-drawer').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');
 assert(drawerBox.y+drawerBox.height<=701,'Keyboard fits viewport');
 const sizes=await p.locator('.auth-generate,.auth-entry-row').evaluateAll(es=>es.map(e=>[e.offsetWidth,e.offsetHeight]));assert.equal(sizes.length,2);assert.deepEqual(sizes[0],sizes[1]);
 const oldUnit=await p.locator('#panel').evaluate(e=>Math.min(44,(parseFloat(e.style.getPropertyValue('--welcome-sheet-height'))-78)/8));
 assert(await p.locator('[data-auth-key="1"]').evaluate(e=>e.offsetHeight>24),'Keypad fits available gap');
 assert(await p.locator('.auth-slide').evaluate((e,old)=>e.offsetHeight>old+3,oldUnit),'Larger slider');
 const b=await p.locator('[data-verify-slider]').boundingBox(),track=await p.locator('.auth-slide').boundingBox();
 await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2-40,b.y+b.height/2,{steps:6});
 const midway=Number(await p.locator('[data-verify-slider]').getAttribute('aria-valuenow'));assert(midway>0&&midway<100);
 assert.equal(await p.locator('.welcome-login-fill').evaluate(e=>e.style.clipPath),'inset(0px '+(100-midway)+'% 0px 0px)');
 await p.screenshot({path:'.tools/auth-coupon-fill-'+width+'.png'});
 await p.mouse.move(b.x+b.width/2-10,b.y+b.height/2,{steps:4});assert(Number(await p.locator('[data-verify-slider]').getAttribute('aria-valuenow'))<midway);
 await p.mouse.move(track.x+b.width/2,b.y+b.height/2,{steps:12});await p.mouse.up();
 await p.waitForFunction(()=>document.getElementById('welcome-gate').hidden);assert.deepEqual(errors,[]);await p.close();
}console.log('PASS auth coupon 320/390: generation, keypad, reversible drag, preview login, no scrolling');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
