const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{for(const width of [320,390,1280]){
  const page=await browser.newPage({viewport:{width,height:760}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',async r=>{
   const url=new URL(r.request().url());
   if(url.hostname!=='127.0.0.1')return r.abort();
   const file=path.join(process.cwd(),'docs',decodeURIComponent(url.pathname));
   if(!file.startsWith(path.join(process.cwd(),'docs')+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return r.fulfill({status:503,body:'{}'});
   const ext=path.extname(file);return r.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[ext]||'application/octet-stream'});
  });
  if(width===320)await page.addInitScript(()=>{
   localStorage.setItem('p2p-welcome-blur-preview','10');
   localStorage.setItem('p2p-welcome-tint-preview','20');
   localStorage.setItem('p2p-welcome-ray-length','180');
  });
  await page.goto('http://127.0.0.1/mini-app.html');
  assert.deepEqual(await page.locator('#welcome-gate').evaluate(el=>({
   blur:el.style.backdropFilter,tint:el.style.getPropertyValue('--welcome-tint'),
   length:el.style.getPropertyValue('--ray-length')
  })),{blur:'blur(0.7px)',tint:'0.9',length:'30%'});
  await page.waitForTimeout(1200);
  await page.evaluate(()=>{for(const r of document.querySelectorAll('#welcome-puzzle-mask rect')){const a=r.getAnimations()[0];if(a){a.pause();a.currentTime=500;}}});
  await page.screenshot({path:`.tools/welcome-puzzle-${width}.png`});
  await page.waitForTimeout(4400);
  await page.evaluate(()=>{for(const r of document.querySelectorAll('#welcome-puzzle-mask rect'))r.getAnimations()[0]?.play();});
  assert(await page.locator('#welcome-gate').isVisible());
  assert.equal(await page.locator('.welcome-shackle').count(),0);
  assert(await page.locator('.usb-wordmark').isVisible());
  assert(await page.locator('.welcome-usb-body').isHidden());
  assert.equal(await page.locator('.welcome-unlock-control').count(),0);
  assert.equal(await page.locator('.usb-fill').evaluate(el=>getComputedStyle(el).fillOpacity),'0');
  assert(await page.locator('#app').evaluate(el=>el.inert));
  await page.screenshot({path:`.tools/welcome-unlocked-${width}.png`});
  const gateRect=await page.locator('#welcome-gate').boundingBox();
  assert.equal(gateRect.width,Math.min(width,450));
  assert.equal(gateRect.x,(width-Math.min(width,450))/2);
  assert(await page.locator('#app').evaluate(el=>el.inert));
  await page.waitForTimeout(1600);
  assert.equal(await page.locator('h1.welcome-brand').evaluate(el=>getComputedStyle(el).opacity),'1');
  await page.locator('.welcome-glint').evaluate(el=>{const a=el.getAnimations()[0];a.pause();a.currentTime=2200;});
  await page.screenshot({path:`.tools/welcome-glint-${width}.png`});
  await page.emulateMedia({reducedMotion:'reduce'});
  assert(await page.locator('.welcome-glint').isHidden());
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.screenshot({path:`.tools/welcome-${width}.png`});
  assert.equal(await page.locator('[data-welcome-register]').count(),0);
  await page.locator('.welcome-login').click();
  assert(await page.locator('#panel').evaluate(el=>el.open));
  await page.waitForTimeout(500);
  await page.screenshot({path:`.tools/welcome-login-${width}.png`});
  await page.keyboard.press('Escape');
  assert(await page.locator('#welcome-gate').isVisible());
  await page.locator('.welcome-login').click();
  assert.equal(await page.locator('[data-demo-partner]').count(),0);
  await page.locator('[data-code-generate]').click();
  const code=await page.locator('[data-code-source]').inputValue();
  assert.match(code,/^\d{4}$/);
  await page.locator('[data-code-entry]').fill(code);
  await page.locator('.welcome-verify').waitFor({state:'visible'});
  await page.waitForTimeout(450);
  const sliderBox=await page.locator('[data-verify-slider]').boundingBox();
  assert(sliderBox.y+sliderBox.height<=760);
  await page.screenshot({path:`.tools/welcome-slider-start-${width}.png`});
  await page.locator('[data-verify-slider]').fill('60');
  assert.equal(await page.locator('[data-verify-slider]').evaluate(el=>el.style.getPropertyValue('--verify-progress')),'60%');
  await page.screenshot({path:`.tools/welcome-slider-${width}.png`});
  assert(await page.locator('.welcome-verify').isVisible());
  await page.locator('[data-verify-slider]').focus();
  await page.keyboard.press('End');
  assert.equal(await page.locator('.welcome-verify output').evaluate(el=>getComputedStyle(el).opacity),'0');
  assert.match(await page.locator('.menu-demo-message').textContent(),/Telegram ID недоступен/);
  assert(await page.locator('#welcome-gate').isVisible());
  await page.evaluate(()=>{freebkDemoSignedIn=true;window.dispatchEvent(new Event('freebk-account-change'));});
  await page.waitForTimeout(500);
  assert(await page.locator('#welcome-gate').isHidden());
  assert.equal(await page.locator('#app').evaluate(el=>el.inert),false);
  await page.evaluate(()=>{freebkDemoSignedIn=false;window.dispatchEvent(new Event('freebk-account-change'));});
  assert(await page.locator('#welcome-gate').isVisible());
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.goto('http://127.0.0.1/mini-app.html?preview=1');
  await page.evaluate(()=>localStorage.setItem('p2p-coupon-draft:local:Марсель Ла',JSON.stringify({picks:[['draft-test',{id:'draft-test',kind:'outcomes',index:0,value:2,fighters:['А','Б'],label:'Победа А',sport:'boxing'}]],stake:'1234',expanded:true})));
  await page.locator('.welcome-login').click();
  await page.locator('[data-code-generate]').click();
  await page.locator('[data-code-entry]').fill(await page.locator('[data-code-source]').inputValue());
  await page.locator('.welcome-verify').waitFor({state:'visible'});
  await page.locator('[data-verify-slider]').fill('100');
  await page.locator('#welcome-gate').waitFor({state:'hidden'});
  assert.equal(await page.locator('#app').evaluate(el=>el.inert),false);
  assert.equal(await page.evaluate(()=>window.ServerAccount.current),null);
  assert.equal(await page.locator('[data-coupon-stake]').inputValue(),'1234');
  await page.locator('[data-coupon-stake]').fill('2345');
  await page.evaluate(()=>{freebkDemoSignedIn=false;freebkDemoPartner='';window.dispatchEvent(new Event('freebk-account-change'));});
  assert(await page.locator('#bet-coupon').isHidden());
  await page.evaluate(()=>{freebkDemoPartner='Марсель Ла';freebkDemoSignedIn=true;window.dispatchEvent(new Event('freebk-account-change'));});
  assert.equal(await page.locator('[data-coupon-stake]').inputValue(),'2345');
  await page.evaluate(()=>panel('Меню',window.freebkMenuContent()));
  await page.waitForTimeout(500);
  const profile=await page.locator('.menu-account-row').boundingBox();
  const marketRow=await page.locator('.markets').boundingBox();
  const sheet=await page.locator('#panel').boundingBox();
  assert(Math.abs(sheet.y-marketRow.y-marketRow.height-12)<2);
  const balance=await page.locator('.menu-balance').boundingBox();
  assert(balance.x>=profile.x+profile.width);
  const avatar=await page.locator('.menu-avatar').boundingBox();
  assert(Math.abs(avatar.y-balance.y)<2);
  assert(Math.abs(avatar.height-balance.height)<2);
  await page.screenshot({path:`.tools/profile-balance-${width}.png`});
  assert.deepEqual(errors,[]);
  await page.close();
 }console.log('Welcome: 320/390, registration notice, close/reopen, login/logout, inert and overflow passed');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
