const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
for(const width of [320,390]){
 const p=await browser.newPage({viewport:{width,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();if(u.pathname.startsWith('/api/'))return r.fulfill({contentType:'application/json',body:'{"events":[]}'});const f=path.join(process.cwd(),'docs',u.pathname);if(!fs.existsSync(f))return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:({'.html':'text/html','.css':'text/css','.js':'text/javascript'})[path.extname(f)]||'text/plain'});});
 await p.goto('http://127.0.0.1/mini-app.html?preview=1',{waitUntil:'networkidle'});
 const fixture={id:'language-fixture',sport:'mma',status:'prematch',title:'MMA · В разработке / Возможные',fighters:['Арман Царукян','Маурисио Руффи'],originalFighters:['Arman Tsarukyan','Mauricio Ruffy'],odds:[1.27,64,3.95],startTime:'2026-09-20T01:00:00Z',date:'20 сентября · 04:00 МСК',priceNote:'1xBet · линия 09.09, 20:00 МСК',cardInfo:{title:'MMA · UFC 331',source:'https://example.com/',stage:'Основной кард'}};
 await p.evaluate(e=>{document.getElementById('welcome-gate')?.remove();document.getElementById('app').inert=false;FightScreen.setEvents([e]);},fixture);
 await p.locator('.tournament>summary').click();
 assert.equal(await p.locator('.original-name').first().isVisible(),false);
 await p.click('[data-language=en]');
 const corpus=['docs/ufc-cards.js','docs/boxing-cards.js'].flatMap(f=>[...fs.readFileSync(f,'utf8').matchAll(/'([^'\n]*[А-Яа-яЁё][^'\n]*)'/g)].map(m=>m[1]));
 const missing=await p.evaluate(texts=>texts.map(source=>({source,en:AppLanguage.translate(source)})).filter(x=>/[А-Яа-яЁё]/.test(x.en)),corpus);
 assert.deepEqual(missing,[],'All editorial MMA/boxing descriptions must have English translations');
 const silva={...fixture,id:'silva-wang',fighters:['Наталия Силва','Ван Цун'],originalFighters:['Natalia Silva','Wang Cong'],cardInfo:{title:'UFC 332 · Силва — Ван Цун · Солт-Лейк-Сити',stage:'Главный бой · За вакантный титул UFC в женском наилегчайшем весе',highlight:'Силва — Ван Цун: за вакантный титул · Женский наилегчайший вес · 5 раундов',source:'https://example.com/'}};
 await p.evaluate(e=>FightScreen.setEvents([e]),silva);
 await p.waitForFunction(()=>document.querySelector('#events')?.textContent.includes('Salt Lake City'));
 assert(!/[А-Яа-яЁё]/.test(await p.locator('#events').innerText()));
 await p.locator('.tournament>summary').click();
 assert(!/[А-Яа-яЁё]/.test(await p.locator('#events').innerText()));
 await p.screenshot({path:'.tools/language-silva-en-'+width+'.png'});
 await p.evaluate(e=>FightScreen.setEvents([e]),fixture);
 await p.waitForFunction(()=>document.querySelector('.fighter-link')?.textContent.includes('Arman Tsarukyan'));
 assert.equal(await p.locator('[data-mode=prematch]').innerText(),'Prematch');
 await p.evaluate(e=>FightScreen.setEvents([{...e,odds:[1.5,50,3]}]),fixture);
 await p.waitForFunction(()=>document.querySelector('.fighter-link')?.textContent.includes('Arman Tsarukyan'));
 assert.equal(await p.locator('[data-sport=boxing] .sport-label').innerText(),'Boxing');
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.screenshot({path:'.tools/language-en-'+width+'.png'});
 const boxing={...fixture,sport:'boxing',title:'Бокс',cardInfo:{title:'Бокс',source:'https://boxing-data.com/docs/endpoints/fights/',stage:'Первый средний вес · 12 раундов · Титулы не указаны в источнике',note:'Boxing Data. Время в расписании — The Odds (МСК); часовой пояс Boxing Data не указан.',stale:true}};
 await p.evaluate(e=>{FightScreen.setEvents([e]);FightScreen.setSport('boxing');openFight(e.id);},boxing);
 await p.waitForFunction(()=>document.querySelector('#fight-live-details')?.textContent.includes('Titles not specified by the source'));
 assert(!/[А-Яа-яЁё]/.test(await p.locator('#fight-live-details').innerText()));
 await p.evaluate(e=>FightScreen.setEvents([{...e,odds:[1.7,40,2.9]}]),boxing);
 await p.waitForFunction(()=>document.querySelector('#fight-live-details')?.textContent.includes('Titles not specified by the source'));
 assert(!/[А-Яа-яЁё]/.test(await p.locator('#fight-live-details').innerText()));
 await p.screenshot({path:'.tools/language-boxing-en-'+width+'.png'});
 await p.evaluate(()=>document.getElementById('panel').close());
 await p.click('[data-language=ru]');
 await p.evaluate(()=>openFight('language-fixture'));
 await p.waitForFunction(()=>document.querySelector('#fight-live-details')?.textContent.includes('Титулы не указаны в источнике'));
 await p.evaluate(()=>document.getElementById('panel').close());await p.click('[data-language=en]');
 await p.reload();await p.waitForFunction(()=>document.documentElement.lang==='en');
 await p.evaluate(()=>{document.getElementById('welcome-gate')?.remove();document.getElementById('app').inert=false;});
 await p.click('[data-language=ru]');
 assert.equal(await p.locator('[data-mode=prematch]').innerText(),'Прематч');
 assert.equal(await p.evaluate(()=>localStorage.getItem('p2p-language')),'ru');
 assert.deepEqual(errors,[]);await p.close();
}console.log('Language: RU/EN, updated events, original names, reload, no overflow 320/390 PASS');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
